-- MySQL Script generated by MySQL Workbench
-- 10/21/16 14:31:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema roomz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema roomz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `roomz` DEFAULT CHARACTER SET utf8 ;
USE `roomz` ;

-- -----------------------------------------------------
-- Table `roomz`.`BLOCO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roomz`.`BLOCO` (
  `ID_BLOCO` INT NOT NULL,
  `NOME_BLOCO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_BLOCO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roomz`.`ANDAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roomz`.`ANDAR` (
  `ID_ANDAR` INT NOT NULL,
  `ID_BLOCO` INT NOT NULL,
  `NOME_ANDAR` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_ANDAR`, `ID_BLOCO`),
  INDEX `fk_ANDAR_BLOCO1_idx` (`ID_BLOCO` ASC),
  CONSTRAINT `fk_ANDAR_BLOCO1`
    FOREIGN KEY (`ID_BLOCO`)
    REFERENCES `roomz`.`BLOCO` (`ID_BLOCO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roomz`.`TIPO_SALA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roomz`.`TIPO_SALA` (
  `ID_TIPO` INT NOT NULL,
  `TIPO_SALA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_TIPO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roomz`.`ESTADOS_SALA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roomz`.`ESTADOS_SALA` (
  `ID_ESTADO` INT NOT NULL,
  `NOME_ESTADO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_ESTADO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roomz`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roomz`.`DEPARTAMENTO` (
  `SIGLA_DEPARTAMENTO` VARCHAR(5) NOT NULL,
  `NOME_DEPARTAMENTO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SIGLA_DEPARTAMENTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roomz`.`SALA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roomz`.`SALA` (
  `ID_SALA` INT NOT NULL,
  `ID_ANDAR` INT NOT NULL,
  `ID_BLOCO` INT NOT NULL,
  `TIPO_SALA` INT NOT NULL,
  `ID_ESTADO` INT NOT NULL,
  `SIGLA_DEPARTAMENTO` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ID_SALA`, `ID_ANDAR`, `ID_BLOCO`),
  INDEX `fk_SALA_TIPO_SALA1_idx` (`TIPO_SALA` ASC),
  INDEX `fk_SALA_ESTADOS_SALA1_idx` (`ID_ESTADO` ASC),
  INDEX `fk_SALA_ANDAR2_idx` (`ID_ANDAR` ASC, `ID_BLOCO` ASC),
  INDEX `fk_SALA_DEPARTAMENTO1_idx` (`SIGLA_DEPARTAMENTO` ASC),
  CONSTRAINT `fk_SALA_TIPO_SALA1`
    FOREIGN KEY (`TIPO_SALA`)
    REFERENCES `roomz`.`TIPO_SALA` (`ID_TIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SALA_ESTADOS_SALA1`
    FOREIGN KEY (`ID_ESTADO`)
    REFERENCES `roomz`.`ESTADOS_SALA` (`ID_ESTADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SALA_ANDAR2`
    FOREIGN KEY (`ID_ANDAR` , `ID_BLOCO`)
    REFERENCES `roomz`.`ANDAR` (`ID_ANDAR` , `ID_BLOCO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SALA_DEPARTAMENTO1`
    FOREIGN KEY (`SIGLA_DEPARTAMENTO`)
    REFERENCES `roomz`.`DEPARTAMENTO` (`SIGLA_DEPARTAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roomz`.`TIPO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roomz`.`TIPO_USUARIO` (
  `TIPO_USUARIO` VARCHAR(20) NOT NULL,
  `RESERVAR_USUARIO` TINYINT(1) NOT NULL,
  PRIMARY KEY (`TIPO_USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roomz`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roomz`.`USUARIO` (
  `COD_USUARIO` INT NOT NULL,
  `NOME_USUARIO` VARCHAR(45) NOT NULL,
  `EMAIL_USUARIO` VARCHAR(45) NOT NULL,
  `SIGLA_DEPARTAMENTO` VARCHAR(5) NOT NULL,
  `TIPO_USUARIO` VARCHAR(20) NOT NULL,
  `KEY_USER` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COD_USUARIO`, `EMAIL_USUARIO`, `KEY_USER`),
  INDEX `fk_USUARIO_TIPO_USUARIO1_idx` (`TIPO_USUARIO` ASC),
  INDEX `fk_USUARIO_DEPARTAMENTO1_idx` (`SIGLA_DEPARTAMENTO` ASC),
  CONSTRAINT `fk_USUARIO_TIPO_USUARIO1`
    FOREIGN KEY (`TIPO_USUARIO`)
    REFERENCES `roomz`.`TIPO_USUARIO` (`TIPO_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_DEPARTAMENTO1`
    FOREIGN KEY (`SIGLA_DEPARTAMENTO`)
    REFERENCES `roomz`.`DEPARTAMENTO` (`SIGLA_DEPARTAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roomz`.`HORARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roomz`.`HORARIO` (
  `ID_HORARIO` VARCHAR(3) NOT NULL,
  `DESC_HORARIO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_HORARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roomz`.`RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roomz`.`RESERVA` (
  `DATA_RESERVA` DATE NOT NULL,
  `ID_SALA_RESERVA` INT NOT NULL,
  `ID_ANDAR_RESERVA` INT NOT NULL,
  `ID_BLOCO_RESERVA` INT NOT NULL,
  `COD_USUARIO_RESERVA` INT NOT NULL,
  `HORARIO_ID_HORARIO` VARCHAR(3) NOT NULL,
  INDEX `fk_RESERVA_SALA1_idx` (`ID_SALA_RESERVA` ASC, `ID_ANDAR_RESERVA` ASC, `ID_BLOCO_RESERVA` ASC),
  INDEX `fk_RESERVA_USUARIO1_idx` (`COD_USUARIO_RESERVA` ASC),
  INDEX `fk_RESERVA_HORARIO2_idx` (`HORARIO_ID_HORARIO` ASC),
  PRIMARY KEY (`ID_ANDAR_RESERVA`, `DATA_RESERVA`, `ID_SALA_RESERVA`, `COD_USUARIO_RESERVA`, `ID_BLOCO_RESERVA`, `HORARIO_ID_HORARIO`),
  CONSTRAINT `fk_RESERVA_SALA1`
    FOREIGN KEY (`ID_SALA_RESERVA` , `ID_ANDAR_RESERVA` , `ID_BLOCO_RESERVA`)
    REFERENCES `roomz`.`SALA` (`ID_SALA` , `ID_ANDAR` , `ID_BLOCO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_USUARIO1`
    FOREIGN KEY (`COD_USUARIO_RESERVA`)
    REFERENCES `roomz`.`USUARIO` (`COD_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_HORARIO2`
    FOREIGN KEY (`HORARIO_ID_HORARIO`)
    REFERENCES `roomz`.`HORARIO` (`ID_HORARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roomz`.`RESERVA_NORMAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roomz`.`RESERVA_NORMAL` (
  `DATA_RESERVA` DATE NOT NULL,
  `SALA_ID_SALA` INT NOT NULL,
  `SALA_ID_ANDAR` INT NOT NULL,
  `SALA_ID_BLOCO` INT NOT NULL,
  `HORARIO_ID_HORARIO` VARCHAR(3) NOT NULL,
  INDEX `fk_RESERVA_SALA1_idx` (`SALA_ID_SALA` ASC, `SALA_ID_ANDAR` ASC, `SALA_ID_BLOCO` ASC),
  INDEX `fk_RESERVA_NORMAL_HORARIO2_idx` (`HORARIO_ID_HORARIO` ASC),
  CONSTRAINT `fk_RESERVA_SALA10`
    FOREIGN KEY (`SALA_ID_SALA` , `SALA_ID_ANDAR` , `SALA_ID_BLOCO`)
    REFERENCES `roomz`.`SALA` (`ID_SALA` , `ID_ANDAR` , `ID_BLOCO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_NORMAL_HORARIO2`
    FOREIGN KEY (`HORARIO_ID_HORARIO`)
    REFERENCES `roomz`.`HORARIO` (`ID_HORARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO departamento VALUES('NN','nullpointer');